package com.qiguliuxing.dts.db.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@TableName("dts_order")
public class Order implements Serializable {
    public static final int PAY_STATE_CREATED = 0;//订单生成待支付
    public static final int PAY_STATE_SUCCESS = 1;//支付成功
    public static final int PAY_STATE_FAIL = 2;//支付失败
    public static final int PAY_STATE_CANCEL = 4;//已取消
    public static final int PAY_STATE_REFUNDED = 5;//已退款
    public static final int PAY_STATE_CLOSED = 6;//订单关闭

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_order.id
     *
     * @mbg.generated
     */
    @TableId(type = IdType.AUTO)
    @TableField("id")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_order.user_id
     *
     * @mbg.generated
     */
    @ApiModelProperty("用户id")
    @TableField("user_id")
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_order.order_sn
     *
     * @mbg.generated
     */
    @ApiModelProperty("订单号")
    @TableField("order_sn")
    private String orderSn;

    /**
     *  订单类型（0.普通订单1.会员订单默认0）
     */
    @ApiModelProperty("订单类型（0.普通订单1.会员订单默认0）")
    @TableField("type")
    private Integer type;

    /**
     *  支付状态: 0-待支付, 1-支付成功, 2-支付失败, 4-已取消, 5-已退款, 6-订单关闭
     */
    @ApiModelProperty("支付状态")
    @TableField("order_status")
    private Integer orderStatus;

    /**
     *  收货人名称
     */
    @ApiModelProperty("收货人名称")
    @TableField("consignee")
    private String consignee;

    /**
     *  收货人手机号
     */
    @ApiModelProperty("收货人手机号")
    @TableField("mobile")
    private String mobile;

    /**
     *  收货人具体地址
     */
    @ApiModelProperty("收货人具体地址")
    @TableField("address")
    private String address;
//    /**
//     *  订单标题
//     */
//    @ApiModelProperty("订单标题")
//    @TableField("subject")
//    private String subject;
//
//    /**
//     *  商品描述信息
//     */
//    @ApiModelProperty("商品描述信息")
//    @TableField("body")
//    private String body;
//
//    /**
//     *  过期时间（秒）
//     */
//    @ApiModelProperty("订单过期时间戳,秒")
//    @TableField("expired_at")
//    private Long expiredAt;

    /**
     *  商品总费用
     */
    @ApiModelProperty("商品总费用")
    @TableField("goods_price")
    private Float goodsPrice;

    /**
     *  配送费用
     */
    @ApiModelProperty("配送费用")
    @TableField("freight_price")
    private Float freightPrice;

//    /**
//     *  渠道订单号
//     */
//    @ApiModelProperty("渠道订单号")
//    @TableField("out_order_no")
//    private String outOrderNo;

//    /**
//     *  渠道支付错误码
//     */
//    @ApiModelProperty("渠道支付错误码")
//    @TableField("err_code")
//    private String errCode;

//    /**
//     *  渠道支付错误信息
//     */
//    @ApiModelProperty("渠道支付错误信息")
//    @TableField("err_msg")
//    private String errMsg;

    /**
     *  支付成功时间
     */
    @ApiModelProperty("支付成功时间")
    @TableField("success_time")
    private LocalDateTime successTime;

//    /**
//     *  订单创建时间
//     */
//    @ApiModelProperty("订单创建时间")
//    @TableField("created_at")
//    private LocalDateTime createdAt;
//
//    /**
//     *  订单更新时间
//     */
//    @ApiModelProperty("订单更新时间")
//    @TableField("updated_at")
//    private LocalDateTime updatedAt;
//
//    /**
//     *  额外参数
//     */
//    @ApiModelProperty("额外参数")
//    @TableField("extra")
//    private String extra;

    /**
     *  用户订单留言
     */
    @ApiModelProperty("用户订单留言")
    @TableField("message")
    private String message;

    /**
     *  买家留言
     */
    @ApiModelProperty("支付宝订单号")
    @TableField("trade_no")
    private String tradeNo;


    /**
     *优惠券减免
     *
     * @mbg.generated
     */
    private BigDecimal couponPrice;

    /**
     *用户积分减免
     *
     * @mbg.generated
     */
    private BigDecimal integralPrice;

    /**
     *团购优惠价减免
     *
     * @mbg.generated
     */
    private BigDecimal grouponPrice;

    /**
     *订单费用， = goods_price + freight_price - coupon_price
     *
     * @mbg.generated
     */
    private BigDecimal orderPrice;

    /**
     *
     *
     * @mbg.generated
     */
    private BigDecimal actualPrice;

    /**
     *
     *
     * @mbg.generated
     */
    private String payId;

    /**
     *
     *
     * @mbg.generated
     */
    private LocalDateTime payTime;

    /**
     *
     *
     * @mbg.generated
     */
    private String shipSn;

    /**
     *
     *
     * @mbg.generated
     */
    private String shipChannel;

    /**
     *
     *
     * @mbg.generated
     */
    private LocalDateTime shipTime;

    /**
     *
     *
     * @mbg.generated
     */
    private LocalDateTime confirmTime;

    /**
     *
     *
     * @mbg.generated
     */
    private Short comments;

    /**
     *
     *
     * @mbg.generated
     */
    private LocalDateTime endTime;

    /**
     *
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     *
     * @mbg.generated
     */
    private BigDecimal settlementMoney;

    /**
     *
     * @mbg.generated
     */
    private Boolean settlementStatus;

}