package com.qiguliuxing.dts.db.domain;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

@Data
@TableName("dts_order")
public class Order implements Serializable {
    public static final int PAY_STATE_CREATED = 0;//订单生成待支付
    public static final int PAY_STATE_SUCCESS = 1;//支付成功
    public static final int PAY_STATE_FAIL = 2;//支付失败
    public static final int PAY_STATE_CANCEL = 4;//已取消
    public static final int PAY_STATE_REFUNDED = 5;//已退款
    public static final int PAY_STATE_CLOSED = 6;//订单关闭

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_order.id
     *
     * @mbg.generated
     */
    @TableId(type = IdType.AUTO)
    @TableField("id")
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_order.user_id
     *
     * @mbg.generated
     */
    @ApiModelProperty("用户id")
    @TableField("user_id")
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dts_order.order_sn
     *
     * @mbg.generated
     */
    @ApiModelProperty("订单号")
    @TableField("order_no")
    private String orderNo;

    /**
     *  会员等级
     */
    @ApiModelProperty("会员等级")
    @TableField("vip_level")
    private Integer vipLevel;

    /**
     *  支付状态: 0-待支付, 1-支付成功, 2-支付失败, 4-已取消, 5-已退款, 6-订单关闭
     */
    @ApiModelProperty("支付状态")
    @TableField("state")
    private Integer state;

    /**
     *  订单标题
     */
    @ApiModelProperty("订单标题")
    @TableField("subject")
    private String subject;

    /**
     *  商品描述信息
     */
    @ApiModelProperty("商品描述信息")
    @TableField("body")
    private String body;

    /**
     *  过期时间（秒）
     */
    @ApiModelProperty("订单过期时间戳,秒")
    @TableField("expired_at")
    private Long expiredAt;

    /**
     *  订单金额
     */
    @ApiModelProperty("订单金额（分）")
    @TableField("fee_amount")
    private Float feeAmount;

    /**
     *  渠道订单号
     */
    @ApiModelProperty("渠道订单号")
    @TableField("out_order_no")
    private String outOrderNo;

    /**
     *  渠道支付错误码
     */
    @ApiModelProperty("渠道支付错误码")
    @TableField("err_code")
    private String errCode;

    /**
     *  渠道支付错误信息
     */
    @ApiModelProperty("渠道支付错误信息")
    @TableField("err_msg")
    private String errMsg;

    /**
     *  支付成功时间
     */
    @ApiModelProperty("支付成功时间")
    @TableField("success_time")
    private LocalDateTime successTime;

    /**
     *  额外参数
     */
    @ApiModelProperty("额外参数")
    @TableField("extra")
    private String extra;

    /**
     *  买家留言
     */
    @ApiModelProperty("买家留言")
    @TableField("user_note")
    private String userNote;

    /**
     *  买家留言
     */
    @ApiModelProperty("支付宝订单号")
    @TableField("trade_no")
    private String tradeNo;

    /**
     *  买家留言
     */
    @ApiModelProperty("订单类型")
    @TableField("type")
    private Integer type;

}